services:
    db:
        build: ./time_series_db
        expose:
            - "3306"
        ports:
            - "3307:3306"
    broker:
        build: ./broker
        expose:
            - "1883"
        ports:
            - "1883:1883"
    catalog:
        build: ./catalog
        expose:
            - "8080"
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/broker"]
            interval: 10s
            timeout: 5s
            retries: 3
        depends_on:
            - broker
    db-adaptor:
        build: ./time_series_db_adaptor
        expose:
            - "8080"
        ports:
            - "8083:8080"
        depends_on:
            - catalog
            - db
            - broker
    sensors:
        build: ./sensors
        expose:
            - "8080"
        ports:
            - "8081:8080"
        depends_on:
            - catalog
            - broker
    actuators:
        build: ./actuators
        expose:
            - "8080"
        ports:
            - "8082:8080"
        depends_on:
            - catalog
            - broker
    weather_adaptor:
        build: ./weather
        ports:
          - "8084:8080"
        restart: always