
services:
  broker:
    build: ./broker
    expose:
      - "1883"
    ports:
      - "1883:1883"

  time_series_db:
    build: ./time_series_db
    expose:
      - "3306"
    ports:
      - "3307:3306"


  time_series_db_adaptor:
    build: ./time_series_db_adaptor
    expose:
      - "8080"
    ports: 
      - "8083:8080"
    depends_on:
      - time_series_db
      - broker
      - catalog

  catalog:
    build: ./catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"  
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/broker"]
        interval: 10s
        timeout: 5s
        retries: 3
    depends_on:
        - broker

  sensors:
    build: ./sensors
    expose:
      - "8080"
    ports:
      - "8081:8080"
    depends_on:
      - broker
      - catalog


  actuators:
    build: ./actuators
    expose:
      - "8080"
    ports:
      - "8082:8080"
    depends_on:
      - broker
      - catalog


  weather:
    build: ./weather
    expose:
      - "8080"
    ports:
      - "8084:8080"


  bot:
    build: ./bot
    expose:
      - "8080"
    ports:
      - "8085:8080"
    depends_on:
      - broker
      - catalog

  led_manager:
    build: ./LEDmanager
    expose:
      - "8080"
    ports:
      - "8086:8080"
    depends_on:
      - broker
      - catalog