
services:
  ###################################################################
  # BROKER (MQTT)
  ###################################################################
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    container_name: broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot_net

  ###################################################################
  # BASE DE DONNÉES MySQL (time_series_db)
  ###################################################################
  time_series_db:
    build:
      context: ./time_series_db
      dockerfile: Dockerfile
    container_name: time_series_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timeseries_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - time_series_db_data:/var/lib/mysql
    networks:
      - iot_net

  ###################################################################
  # ADAPTATEUR time_series_db_adaptor
  ###################################################################
  time_series_db_adaptor:
    build:
      context: ./time_series_db_adaptor
      dockerfile: Dockerfile
    container_name: time_series_db_adaptor
    depends_on:
      - time_series_db
    environment:
      DB_HOST: time_series_db        # <-- Le nom du service ci-dessus
      DB_NAME: timeseries_db         # <-- Doit correspondre à la variable MYSQL_DATABASE
      DB_USER: admin
      DB_PASSWORD: admin
      DB_PORT: "3306"
    networks:
      - iot_net

  ###################################################################
  # CATALOG
  ###################################################################
  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    container_name: catalog
    depends_on:
      - broker
      - time_series_db
    ports:
      - "8081:8080"  # si ton code écoute sur 8080, tu peux mapper 8081:8080 par exemple
    networks:
      - iot_net

  ###################################################################
  # SENSORS
  ###################################################################
  sensors:
    build:
      context: ./sensors
      dockerfile: Dockerfile
    container_name: sensors
    depends_on:
      - broker
      - catalog
    networks:
      - iot_net

  ###################################################################
  # ACTUATORS
  ###################################################################
  actuators:
    build:
      context: ./actuators
      dockerfile: Dockerfile
    container_name: actuators
    depends_on:
      - broker
      - catalog
    networks:
      - iot_net

  ###################################################################
  # WEATHER
  ###################################################################
  weather:
    build:
      context: ./weather
      dockerfile: Dockerfile
    container_name: weather
    depends_on:
      - broker
      - catalog
    networks:
      - iot_net

  ###################################################################
  # BOT
  ###################################################################
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - broker
      - catalog
    networks:
      - iot_net

networks:
  iot_net:

volumes:
  time_series_db_data:
